### ISSUE TITLE
Scoring examples in Python

### ISSUE THREAD

**Issue by BramVanroy** [flipz357/smatchpp#3]
Thanks for this library!

It would be great if the API had some easy access point for scoring in Python, like

- `score(graph_a: str, graph_b: str)`: scoring two penman graphs against each other
- `score_all(graphs_a: List[str], graphs_b: List[b])`: scoring two corpora against each other

That should make it easier to use the library during machine learning experiments, for instance. It is currently not clear how that can be done.

There are some Python examples [here](https://github.com/flipz357/smatchpp#pip-install) but for someone who does not know the implementation details it is hard to know what to use. In other words, how can I do the same commands as written [here](https://github.com/flipz357/smatchpp#example-configurations-for-evaluation) but directly in Python and not with files but with in-memory objects (lists of penmans)?

Thanks

**Comment by flipz357** [comment]
Great suggestion. Examples of how to do what you're interested in are now, since commit 7d0d642, in [Example I](https://github.com/flipz357/smatchpp#example-i-smatch-matching-with-some-basic-default) and for optimal matching in [Example II](https://github.com/flipz357/smatchpp#example-iii-smatch-matching-same-as-default-but-with-ilp). 

The functions you mentioned are accessible as

```
measure.score_pair
```

and

```
measure.score_corpus
```

It seems that only the first is described currently in the README, I will add some information on how to score corpus, too, so leaving this open.

**Comment by BramVanroy** [comment]
Thank you, that looks great! Looking forward to using it from a new PyPi release.

**Comment by flipz357** [comment]
Description on pair matching/scoring is now in Examples [I](https://github.com/flipz357/smatchpp#example-i-smatch-matching-with-some-basic-default), [II](https://github.com/flipz357/smatchpp#example-ii-smatch-matching-same-as-default-but-with-ilp) and [III](https://github.com/flipz357/smatchpp#example-iii-best-practice-matching-for-a-pair-of-amr-graphs). Description for corpus scoring like  in `score.sh` but from python interface is in [Example IV](https://github.com/flipz357/smatchpp#example-iv-best-practice-for-amr-corpus-scoring).

[edit: fix format]

**Comment by BramVanroy** [comment]
This looks exactly like what I need. Thank you so much! Feel free to close this topic.
