### ISSUE TITLE
difference with Smatch

### ISSUE THREAD

**Issue by jheinecke** [flipz357/smatchpp#8]
Hi
after creating an issue for https://github.com/snowblink14/smatch I found a case where Smatch and Smatchpp score very differently, and I'm not sure which is the ideal/correct score:

```
# ::snt The boy is a hard worker.
(p / person
      :domain (b / boy)
      :ARG0-of (w / work-01
            :manner (h / hard)))
```
and `
```
(w / worker
      :mod (h / hard)
      :domain (b / boy))
```

give Precision: 0.5000, Recall: 0.6667, F-score: 0.5714 with Smatch and
F1: 42.86    Precision: 37.5    Recall: 50.0 with Smatchpp (with hillclimber and ilp)
Which score is correct ?
Transformed in triples (S,P,O) the two graphs correspond to

```
TOP     :top            p
p	:instance	person
b	:instance	boy
w	:instance	work-01
h	:instance	hard
p	:domain	        b
w	:ARG0	        p
w	:manner         h
```
(8 edges)

and

```
TOP     :top            w
w	:instance	worker
h	:instance	hard
b	:instance	boy
w	:mod	        h
w	:domain 	b
```
(6 edges)

Smatch (-v) aligns p(person)-w(worker) b(boy)-b(boy) w(work-01)-Null h(hard)-h(hard) (2 correct)
and aligns the incoming relations domain and top (another 2). 
that is 4 matches, with 8 in the first and 6 in the second graphs it calculates recall 4/8 (0.5), precision 6/8 (0.66...) and F1 (`2*P*R/(R+P)` = 0.5714)

Who is right in your opinion, smatch or smatchpp ? Evaluation of AMR predictions depend on this, for instance a prediction on the AMR3.0 test file scores P: 0.8071, R: 0.8371, F1: 0.8218 with Smatch (micro) and P: 80.5, R: 83.44, F1: 81.94 with SmatchPP (micro).

**Comment by flipz357** [comment]
@jheinecke If the search space is small, as in your example, hill-climber and ilp find the same solution. So your example is very interesting since it shows some conceptual difference.

On your example. Let's start with noting that it makes sense to align, h-h, b-b, p-w. Same as the alignment that you printed.

However, with this alignment I see three matching edges, not four:

```
(p|w) :domain (b|b)
(b|b) :instance boy
(h|h) :instance hard
```

The top of the amr indicates the focus of the sentence. Since the focus is different (different strings), I don't see why Smatch would find that the focus is matching and adds another matching triple? Do you have an idea?

I think it maybe depends on how you model the (hidden) top triple:

```
(top, :top, p) and (top, :top, w)          # this adds a matching triple since (w|p)

or 

(p, :top, person) and (w, :top, worker)        # this doesn't add a matching triple
```

Smatchpp sets the second as default, since from the AMR view it imo makes more sense like this. E.g., consider the AMRs `(d / duck)` and `(c / car)` --- do these AMRs have the same TOP/focus? Imo, no. I also thought that I've seen Smatch use the second variant, too.

**Comment by flipz357** [comment]
I think I can confirm there are two approaches of modeling the root which return different scores.

In the latest commit in Smatch the modeling of root has changed.

As I see it, before the change, Smatch modeled the root as:

```
(p, :top, person) and (w, :top, worker)
```

which is what SMATCH++ does.

And since the [last commit](https://github.com/snowblink14/smatch/commit/842bc9f7b325f47606351cd3fb4fc00c594af0b0), Smatch has changed to

```
(p, :top, top) and (w, :top, top)
```

 I think the commit wanted to simplify stuff and maybe wasn't aware that the score could change. 
 
 @goodmami do you have an idea on how focus/root should be treated?

**Comment by jheinecke** [comment]
The smatch I play with is a recent clone (last week) so, I should use the latest commit. You are right that smatch takes the top as matching if the first node matches (it outputs P/R/F 0.5/0.5/0.5 for the graphs `(c / cat)` and `(d / dog)` whereas smatchpp outputs 0/0/0 (which I prefer). 

What is used in official AMR inference ?

**Comment by flipz357** [comment]
Yes, I prefer it too. I think SMATCH++ (and the old version of Smatch) do it more correctly.

The [AMR guidelines](https://github.com/amrisi/amr-guidelines/blob/317682968a61075f577e70c02888b155d163ab8a/amr.md?plain=1#L2090) also specifically talk about *root concept*, e.g.:

```
The concept of focus only applies at the very top (root) of the AMR. After a root concept is selected, there are no more focus considerations
```

I guess this makes sense, since "sentence focus" is a specific semantic thing that can't be expressed with only a variable and if we would do so, as you have also showed, it would result in cases that seem a bit awkward, such as a Smatch score of 0.5 for `(c / cat)` and `(d / dog)` due to purportedly same focus, but these two AMRs/sentences don't actually have the same focus.

**Comment by goodmami** [comment]
> I think the commit wanted to simplify stuff and maybe wasn't aware that the score could change.
>
> @goodmami do you have an idea on how focus/root should be treated?

It wasn't about simplifying things, and it was intentional that the score changed. The purpose was to address the double-penalty of getting the top concept wrong. For context, see the discussion on https://github.com/snowblink14/smatch/issues/25

It made sense at the time, but in retrospect it may have been a hasty decision and the original might be more "correct". The idea is that we identify the top node (its position and what it links to) rather than just the concept of the top node.

Consider:

```amr
# a
(a / alpha
   :ARG0 (b / beta))

# b
(b / beta
   :ARG0-of (a / alpha))

# c
(c / cat)

# d
(d / dog)

# a2
(a / alpha2
   :ARG0 (b / beta))

# b2
(b / beta
   :ARG0-of (a / alpha2))
```

The scores from Smatch are:

| Comparison | `:TOP (concept)` | `:TOP top` | Smatch++ |
| ---------- | ---------------- | ---------- | -------- |
| a, b       | 0.75             | 0.75       | 0.75     |
| c, d       | 0.00             | 0.50       | 0.00     |
| a, a2      | 0.50             | 0.75       | 0.50     |
| a, b2      | 0.50             | 0.50       | 0.50     |

The (a, b) case is not controversial and all implementations get the same score. I think I prefer the original/smatch++ score of 0.0 for the (c, d) case; otherwise nothing will have a score of 0.0 and all it's saying is "these are two graphs that both have a top node". For the (a, a2) case there's more room for discussion. Structurally they are the same and have the same node-node relation and the same concept for `b`, but only a different concept for `a`. Compare that to (a, b2), where not only has the concept of `a` been changed, but the top is now `b` (i.e., the target of the `:ARG0` relation instead of the source and the node whose concept is `beta`). Original Smatch and Smatch++ see no numerical difference between the last two comparisons, but current Smatch does.

That all said, if you asked me today what is the better option, I'd probably go with the original/Smatch++ implementation, especially considering the line you quoted from the AMR guidelines. But the current implemenation is not simply an accident or oversight; it was deliberate.

**Comment by flipz357** [comment]
Thanks for the input @goodmami, seems like we now tend to agree that the way of SMATRCH++ and "old" Smatch is the better option. 

Maybe, to help make things more explicit, when reading a graph in Penman format (possibly processing other AMR graphs than AMR), the root triple can be modeled as

```
variable :root ROOT
```

but when going to AMR and applying AMRStandardizer we explicitly change the triple to

```
variable :root root_concept 
```

or even to

```
variable :focus root_concept
```

As I see now, the second one is already kind of implemented in SMATCH++. I think I could write a more detailed comment in the source code of AMRStandardizer and then the issue could be closed. Do you think the second option or the third option would be nicer for AMR? They don't lead to a change in score, but maybe 3rd is more explicit?

**Comment by flipz357** [comment]
With commit 11b30f3 the issue can now be closed.

The consensus is: Smatch++ does it in the right way. 

To make it more explicit and transparent what is happening, according to the motivation that we discussed in this thread, I added [comments to the code](https://github.com/flipz357/smatchpp/blob/c783d49d3e98e0478a7f9bc386374ae1c5e2a1b7/smatchpp/preprocess.py#L56) of the AMRStandardizer in the appropriate place.

Many thanks to @jheinecke  and @goodmami for the helpful input

**Comment by goodmami** [comment]
> The consensus is: Smatch++ does it in the right way.

That's not what I intended to say, hence the scare-quotes around "correct" in my reply above. I'd agree that the original-Smatch/Smatch++ is preferred in more cases, but there is value in the current-Smatch method, too, namely the ability to distinguish between (a, a2) and (a, b2) above.

For a more practical example, imagine two graphs whose only difference is the top concept of `abandon-01` vs `abandon-02`, which may be a reasonable mistake from a parser. They both have 3 arguments, and 2 of them are exactly the same. Getting the top concept wrong seems like 1 error, not 2.

That said, I think your approach with the `use_concept_as_root` flag is a good way to go.

**Comment by flipz357** [comment]
@goodmami Yeah... I think I see what you mean, and sorry if I misinterpreted a bit what you said. But don't you think this issue should be handled by kind of a different metric?

What I mean is if you make the argument of abondon-01 vs. abondon-02 I think it's better to use another metric that exactly targets such issues, like the [S2match](https://aclanthology.org/2020.tacl-1.34/) metric... it would see that the two abondons that you mentioned are similar. And then you might as well make the argument that `(k / kitten)` and `(c / cat)` shouldn't get a score of 0.0. And so on...

So again, I think I see what you mean and I agree with you (it goes into the direction of my PhD thesis actually), but I think if folks want to use structural Smatch for AMR evaluation, from the standpoint of structural matching and AMR guidelines, it makes the most sense the way that it's now implemented as default in SMATCH++.

For all other stuff (that may as well conceptually even be better), different metrics or Smatch derivatives should be described. To flexibly allow this is exactly one of the goals of SMATCH++. E.g., I outlined how you flexibly can implement your own notion of Smatch triple matching, see [here](https://github.com/flipz357/smatchpp/blob/main/smatchpp/score.py) for a few examples, it can be extended with a custom class.

**Comment by flipz357** [comment]
@goodmami Small addition, maybe it's of interest to you: If you have an idea of a metric that work's better, you can test it empirically against human ratings on [parsing evaluation](https://arxiv.org/abs/2210.06461), [sentence similarity](https://arxiv.org/abs/2108.11949) and now even [NLI](https://arxiv.org/abs/2306.00936), for testing subgraph metrics like precision. All benchmark data is freely available on github. You could even inspect the empirical difference  of the idea with the concept as root or without.

How Smatch is currently mostly applied (only in micro mode, and reporting a single number), my standpoint is basically just that I fear it's not really a good metric for measuring parsing progress anymore, especially in times of [strong parsers](https://arxiv.org/abs/2210.06461). So if we want to keep using Smatch (which is fine and good of course, best together with other metrics though) at least we should try evaluate with Smatch as transparently and as reproducibly and as standardized as possible, producing most meaningful scores... that's the goal of the default setup of SMATCH++.

**Comment by goodmami** [comment]
> What I mean is if you make the argument of abondon-01 vs. abondon-02 I think it's better to use another metric that exactly targets such issues, like the [S2match](https://aclanthology.org/2020.tacl-1.34/) metric...

No, I don't mean to give some non-zero score to semantically similar concepts, though I see the value of such metrics in the broader discussion of computing semantic similarity. Here I'm speaking specifically about Smatch and the reasoning for counting the top concept versus the top node. I mean that if an annotator had a sentence like _The tinkerer abandoned the screwdriver_ and came up with:

```
(a / abandon-01
   :ARG0 (p / person
            :ARG0-of (t / tinker-01))
   :ARG1 (s / screwdriver))
```

...then at least two choices have been made:
1. (lexical) The concept for the word _abandoned_ is `abandon-01`
2. (structural) The `abandon-01` concept is the distinguished top node of the graph; i.e., it's the main predicate or focused concept of the sentence (as opposed to `tinker-01` (_The person who abandoned their screwdriver tinkered_), `person` (_The tinkerer who abandoned their screwdriver_), etc.)

Had they chosen `abandon-02` instead, and if this was the only difference from the gold annotation, then there may be a lexical mistake, but structurally there is no mistake.

Thanks for the paper links and discussion! And, again, I'm not saying that I think Smatch++ should have a different default, and I like that there's a flag to toggle the behavior. Maybe Smatch should have a similar option.

Side note: Even the [FrameNet roleset for "abandon"](http://propbank.github.io/v3.4.0/frames/abandon.html) says that it is undecidable whether to use `abandon-01` or `abandon-02` without an `:ARG2`, but I'm not proposing that the metric account for that. The following sentences are less ambiguous:

* _The tinkerer abandoned the screwdriver as their favorite tool._ (`abandon-01`)
* _The tinkerer abandoned the screwdriver for a proper nail set._ (`abandon-02`)

**Comment by flipz357** [comment]
Thanks, I think I now better understand what you mean. The tinker example is intuitive and in this case I see that we can make the argument that the root concept would be understood as the same in both options. But probably, for the average case in AMR evaluation, it is better as it is now implemented. 

I'm currently working on some refactoring that has some refinements also regarding this issue:

1. Allows to set a simple flag `-graph_type` in the command line. Setting it to `generic` performs some generic pre-processing (lower-casing, edge inversion, etc.). Setting it to `amr` performs advanced preprocessing, including using the concept as root. Not setting the argument at all would process the graphs as they come, doing no pre-processing whatsoever. This would also intuitively/transparently distinguish how much an evaluation is biased by assumptions. For showing how to do custom operations directly using the python package, I'll add a new [example](https://github.com/flipz357/smatchpp/tree/refactor#example-ix-plug-in-custom-standardizer-in-the-matching)

2. It occured to me that there is a hypothetical special case that could be an issue (this may also be a problem in the "original" Smatch): If a penman string has a explicit relation `:root` (sometimes called `:top`) then there will be ambiguity. To mitigate this hypothetical issue, there will be a warning raised in case of when there are explicit `:root` relations in the Penman graph.

**Comment by flipz357** [comment]
Now with the latest release SMATCH++ allows three options from command line:

`-graph_type generic`: basic pre-processing, lower-casing, remove quotes, edge inversion

`-graph_type amr`: amr focused pre-processing, same as generic, but also dereification and amr edge inversion (mod-domain-of) and concept as root

If we don't set graph type: we do no pre-processing at all. E.g., the triples (x, instance, cat) and (x, instance, "cat") wouldn't match.

As a quick inspection of the differences (@jheinecke), I evaluated a parser:

No-preprocessing: F1: 71.31    Precision: 72.82    Recall: 69.86
Generic pre-processing:  F1: 75.39    Precision: 76.99    Recall: 73.85
AMR pre-processing:       F1: 75.19    Precision: 76.8    Recall: 73.64

This shows that setting concept as root deflates the score. The differences in macro (sentence average) Smatch is even larger (AMR type: 76.22 vs. generic type: 76.79), which makes sense, since smaller graphs are more affected by the stricter focus scoring, just again consider "(c / cat)" vs. "(h / house)" = 0.5 with less strict root, and 0.0 with strict root.

**Comment by jheinecke** [comment]
Thanks for this work !
Now we have a new problem in the eternal race for the best SOTA: All papers trying to announce a better score for parsing AMR3.0 test, will use different tools and in case of Smatch++ different configurations to push numbers towards 100. So it will be more difficult to choose the best parser/configuration. strict root seems to be important in my view, but if less strict root gives better results, what will people choose in their papers ;-)

**Comment by flipz357** [comment]
Yes... this may be a problem... seems that numbers chasing can't be helped... (without an unlikely change in attitude of the entire field...). 

Maybe we can pretend that the root treatment doesn't lead to score increment. Since the score-increasing root treatment is a fairly recent commit in Smatch, I think people that used the original Smatch before 2020 didn't increase their score with the "root thing", and then there's also seems to be other parsing evaluation scripts that people are using like "amr-evaluatuion-enhanced" which I think is also based on Smatch pre-2020, so it probably also doesn't inflate with the root.

By the way, the ILP leads also to some score increase. This kind of score increase is totally justified, in fact, it shows the true Smatch. So this should make folks happy :-)

**Comment by flipz357** [comment]
Just for documentation, there is another difference with current Smatch @jheinecke 

Smatch gives these two graphs a score of 1.00:

```
(s / see-01
   :ARG0 (p / person
         :name (n / name
              :op1 "Hans Meier")))
```
and

```
(s / see-01
   :ARG0 (p / person
         :name (n / name
              :op1 "Hans")))
```

whereas the score of Smatch++ does not match the triple (n, op1, "Hans") and (n, op1 "Hans Meier").

This also can lead to unjustified score inflation when using Smatch.

**Comment by jheinecke** [comment]
Yes, I remarked this. But we could accept this, since a space in a litteral is not valid AMR/Penman. But smatch should issue a warning at least

**Comment by flipz357** [comment]
I thought the "" would be a neat way to represent whatever string object, also as a fallback. Can you link in the AMR guidelines that space in a literal is not valid?

I don't think it can be accepted. Clearly the two graphs are different, and also different in meaning. A warning would be kind of very weird, no? "Two graphs are different, but I take them as the same anyway"

**Comment by jheinecke** [comment]
I meant smatch should output warning that the AMR input is invalid (as it does already if the penman is invalid) and ignoring the sentence. 
It is not said explicitly in the AMR guidelines that spaces are not allowed in strings but all examples with spaces use :op1, :op2 etc in https://github.com/amrisi/amr-guidelines/blob/master/amr.md#named-entities

**Comment by flipz357** [comment]
[Here](https://github.com/amrisi/amr-guidelines/issues/271) in the third example that also Nathan said was the right way of representing it, you see string entity with spaces.

Anyways, I find your idea to throw out invalid AMRs from the scoring quite interesting! As an optional setting in SMATCH++ this should be quickly implemented!

For now the SMATCH++ philosophy in case a graph is broken (or we detect it as an "invalid" AMR in the case of when processing AMR) is to issue warning and then rescue as many triples as possible, to treat all parsers fairly. 

But your idea would be an interesting option.

**Comment by jheinecke** [comment]
I found the reference about no spaces, it's not on the AMR site but said in the documentation of the penman library: https://penman.readthedocs.io/en/latest/notation.html 
We should ask Nathan about the spaces, the question in the thread you cite was about keeping AMR as a string or parse it as AMR, and not whether or not it may contain white spaces

**Comment by flipz357** [comment]
Yes, you are right, but consider that the example can be quickly adapted:

`The string "    " represents four whitespaces.`

I don't see how you can model it without whitespaces in amr-string without destroying the meaning. On the other hand, using white spaces in amr literal would be a neat solution to represent the sentence.

**Comment by jheinecke** [comment]
Interesting case. My parser produces
```
(r / represent-01
    :ARG0 (s / string-entity
        :value "")
    :ARG1 (w / whitespace
        :quant 4))
```
which is not quite what I expected :-). I asked Nathan in the issue which you cited

**Comment by goodmami** [comment]
> I found the reference about no spaces, it's not on the AMR site but said in the documentation of the penman library: https://penman.readthedocs.io/en/latest/notation.html

Firstly, the Penman library is not an official source of truth regarding AMR. I just tried to capture and formalize the notation a bit.

Secondly, I think you're referring to this part:

> ```
> # Syntactic productions (whitespace is allowed around non-terminals)
> Start     <- Node
> Node      <- '(' Variable NodeLabel? Relation* ')'
> NodeLabel <- '/' Concept Alignment?
> Concept   <- Constant
> Relation  <- Role Alignment? (Node / Atom Alignment?)
> Atom      <- Variable / Constant
> Constant  <- String / Symbol
> Variable  <- Symbol
>
> # Lexical productions (whitespace is not allowed)
> Symbol    <- NameChar+
> Role      <- ':' NameChar*
> Alignment <- '~' ([a-zA-Z] '.'?)? Digit+ (',' Digit+)*
> String    <- '"' (!'"' ('\\' . / .))* '"'
> NameChar  <- ![ \n\t\r\f\v()/:~] .
> Digit     <- [0-9]
> ```

If so, you may be misunderstanding the comments about whitespace. To keep the grammar easily readable, I did not explicitly encode where whitespace could appear between terms in the productions. So in the first block, you could imagine a production could be rewritten as:

```
NodeLabel <- '/' WS* Concept WS* Alignment?

# also add:
WS <- [ \n\t\r\f\v]  # intervening whitespace
```

In the second block, those are more like token patterns, so whitespace should not be expected in between terms (e.g., you can't get a role with spaces like `: ARG0`). If whitespace was not allowed in strings, I would have had something like:

```
String    <- '"' (!'"' ('\\' NonWS / NonWS))* '"'
NonWS     <- !WS .
```

Whitespace is not allowed in unquoted sequences of characters, such as symbols and roles, which is why `NameChar` specifically disallows it.

I can see how my comments in the grammar above are confusing. Perhaps I should just make it a fully valid grammar.

**Comment by flipz357** [comment]
Thanks for the input @goodmami and asking Nathan @jheinecke 

If I may summarize:

- Space is allowed in string literals enclosed by ""/'', both in AMR and other (rooted) DAGs expressed in "Penman" format

- For metric this means: SMATCH++ does it correctly and it's yet another bug/feature that yield wrong scores in Smatch

**Comment by jheinecke** [comment]
I copy the the link to AMR documentation which says so here: https://www.isi.edu/~ulf/amr/lib/amr-dict.html#string-entity

**Comment by goodmami** [comment]
@flipz357 One small nitpick:

> Space is allowed in string literals enclosed by ""/''

Penman and Smatch both only support double-quoted strings (`"..."`), not single-quoted ones (`'...'`).

**Comment by flipz357** [comment]
Ha, thanks for the correction @goodmami ... This all may seem like a superfluous detail, but it sometimes can have strong implications! I remember that I once evaluated a parser that didn't use quotes, and with one of the Smatch metrics that are floating around (can't remember which one) it scored around 0.70, and with another Smatch it scored 0.80 or something. The lower score was due to not matching strings that in the AMR3 SemBank are enclosed with "".

I guess (correct me if wrong) that the 0.70 would also happen when you would use Penman for loading, since it doesn't do any standardization and takes the quotes as is (which is actually correct since Penman, as I understand it, is for reading graphs as is). But this is explicitly different with SMATCH++ that tries to use standardization explictly. So for the sake of evaluating parsers/graph similarity I think it may be best practice to remove all types of enclosing quotes with explicit Standardizers (just as it is done currently).

**Comment by goodmami** [comment]
> I guess (correct me if wrong) that the 0.70 would also happen when you would use Penman for loading, since it doesn't do any standardization and takes the quotes as is (which is actually correct since Penman, as I understand it, is for reading graphs as is).

I would suspect so, unless any postprocessing of the triples is done:

```pycon
>>> g1 = penman.decode(r'(a / alpha :op1 foo)')
>>> g2 = penman.decode(r'(a / alpha :op1 "foo")')
>>> g1 == g2
False
>>> g1.triples[1]
('a', ':op1', 'foo')
>>> g2.triples[1]
('a', ':op1', '"foo"')
```

I recall the reason Penman doesn't normalize away the quotation marks is rather mundane: to be able to distinguish (and reproduce on encoding) the difference between quoted strings and symbols (things like `:mode imperative`, not `:mode "imperative"`; or `:polarity -`, not `:polarity "-"`). The quotation marks are just part of PENMAN notation's syntax to indicate a string value; they shouldn't be considered part of the content of the string, but I think the symbolic values, like Enums in various programming languages, are inherently different than string values. I see nothing wrong with normalizing quotation marks out of strings during evaluation if it's done consistently and doesn't conflate intentional distinctions in strings vs symbols.

A potential alternative for Penman is to wrap the symbols in a special class. E.g.:

```python
class Symbol(str):
    """Subclass of str for unquoted symbolic values."""
```

That would make it easier to avoid this issue:

```python
>>> penman.encode(penman.Graph([('a', ':instance', 'a space')]))
'(a / a space)'
```

**Comment by flipz357** [comment]
> if it's done consistently 

yup, that's the goal of SMATCH++. In your example:

```
>>> g1 = penman.decode(r'(a / alpha :op1 foo)')
>>> g2 = penman.decode(r'(a / alpha :op1 "foo")')
>>> g1 == g2
False
>>> GenericStandardizer().standardize(g1.triples) == GenericStandardizer().standardize(g2.triples)
True
```

> and doesn't conflate intentional distinctions in strings vs symbols

This may be theory specific, for which custom standardizer can be implemented.
